/// <reference path="jquery-ui-1.12.1.js" />
/// <autosync enabled="true" />
/// <reference path="../client scripts/mvcfoolproof.unobtrusive.min.js" />
/// <reference path="../client scripts/mvcfoolproofjqueryvalidation.min.js" />
/// <reference path="../client scripts/mvcfoolproofvalidation.min.js" />
/// <reference path="bootstrap.min.js" />
/// <reference path="jquery.validate.min.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-3.1.1.js" />
/// <reference path="jquery-3.1.1.min.js" />
/// <reference path="jquery-3.1.1.slim.min.js" />
/// <reference path="jquery-ui-1.12.1.min.js" />
/// <reference path="modernizr-2.8.3.js" />
/// <reference path="respond.matchmedia.addlistener.min.js" />
/// <reference path="respond.min.js" />
